name: Build Monitoring

on:
  workflow_dispatch:
  schedule:
    # 7pm UTC is 10am PDT.
    - cron: '0 19 * * *'

jobs:
  build-report:
    name: Analyze connectors's build results and send report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: check version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests slack_sdk_blaaaaaaaaaaaaaaa
      - name: Run build monitoring script
        run: python ./tools/bin/build_monitoring.py
        env:
          SLACK_BUILD_MONITORING: ${{ secrets.SLACK_BUILD_MONITORING }}
      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_SLACK_WEBHOOK }}
          SLACK_USERNAME: Buildozer
          SLACK_ICON: https://avatars.slack-edge.com/temp/2020-09-01/1342729352468_209b10acd6ff13a649a1.jpg
          SLACK_COLOR: DC143C
          SLACK_TITLE: 'Failed to create report https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}'
          SLACK_FOOTER: ""
