name: Build Monitoring

on:
  workflow_dispatch:
  schedule:
    # 7pm UTC is 10am PDT.
    - cron: '0 19 * * *'

jobs:
  build-report:
    name: Analyze connectors's build results and send report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: check version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests slack_sdk
      - name: Run build monitoring script
        run: python ./tools/bin/build_monitoring.py
        env:
          SLACK_BUILD_MONITORING: ${{ secrets.SLACK_BUILD_MONITORING }}
