# This is a basic workflow to help you get started with Actions

name: TESTCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false
jobs:
  build-cdk-with-all-envs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      
      - uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.7.9
          versions: 3.7.0, 3.8.5, 3.9.0
          
      - name: Create virtualenv for python 3.7.9
        run: pyenv local 3.7.9 && ./gradlew --no-daemon :airbyte-cdk:python:build
          
      - name: Create virtualenv for python 3.7.0
        run: pyenv local 3.7.0 && ./gradlew --no-daemon :airbyte-cdk:python:build
  
      - name: Create virtualenv for python 3.8.5
        run: pyenv local 3.8.5 && ./gradlew --no-daemon :airbyte-cdk:python:build

      - name: Create virtualenv for python 3.9.0
        run: pyenv local 3.9.0 && ./gradlew --no-daemon :airbyte-cdk:python:build
        
        
  build-cdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.7.1 - is a minimal of 3.7.X version supported by github actions
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Build CDK Package
        run: ./gradlew --no-daemon :airbyte-cdk:python:build
