# This is a basic workflow to help you get started with Actions

name: TESTCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false
jobs:
  build-cdk-with-all-envs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: gabrielfalcao/pyenv-action@v7
        with:
          versions: 3.7.0, 3.7.9, 3.8.10, 3.9.5
          commands: pyenv install --list
          
      - name: Create virtualenv for python 3.5.7
        run: pyenv local 3.7.0 && && ./gradlew --no-daemon :airbyte-cdk:python:build
      
      - name: Create virtualenv for python 3.6.8
        run: pyenv local 3.7.9 && ./gradlew --no-daemon :airbyte-cdk:python:build
      
      - name: Create virtualenv for python 3.7.2
        run: pyenv local 3.8.10 && ./gradlew --no-daemon :airbyte-cdk:python:build
